const books = [
  "Svájc",
  "Franciaország",
  "Finnország",
  "Görögország",
  "Európai miniállamok",
  "Egyiptom",
  "Dánia",
  "A különös tanítvány",
  "Üvöltő szelek",
  "Emberi sors",
  "Csendes Don I-IV.",
  "Quo Vadis",
  "Kereszteslovagok I-II.",
  "Édentől keletre I-II.",
  "Vanina vanini",
  "Vörös és fekete",
  "Vörös és fehér",
  "Hamlet. Szentivánéji álom",
  "Lear király",
  "Sok hűhó semmiért",
  "Tragédiák",
  "A nagy utazás",
  "Szerelmi történet",
  "Oliver története",
  "A szuzai menyegző",
  "Színművek",
  "Káin és Ábel. Anyám könnyű álmot ígér",
  "Omló egek alatt",
  "Síkaszói fenyőforgácsok",
  "Advent a Hargitán",
  "Az Idő markában",
  "A lőtt lábú madár nyomában",
  "Kék álhalál",
  "Anyám könnyű álmot ígér",
  "A világ fővárosai",
  "Évezredek hangszerei",
  "Vincent van Gogh",
  "Tiziano",
  "World Wide Web",
  "Linux hálózatok",
  "UNIX felhasználói ismeretek",
  "Linux az otthoni PC-n",
  "A C programozási nyelv",
  "Programozási feladatok I-II.",
  "A WEB programozása I-II.",
  "Adatbázisok",
  "Adobe Photoshop",
  "Hangszerek kislexikona",
  "Zenei lexikon I-III.",
  "A zene könyve",
  "És ilyen a boksz?",
  "Jazz",
  "Halhatatlan Beatles",
  "A fizika kultúrtörténete",
  "Kis fizika I-II.",
  "Sugárözönben élünk",
  "Klasszikus fizika",
  "Miért piros a tilos?",
  "300 kérdés és válasz a fizika köréből",
  "150 kérdés és válasz a fizika köréből",
  "Mindenki fizikája",
  "Fizika",
  "Fizika I-II.",
  "Yesterday",
  "Jazz-zenészek lexikona",
  "Az ember zenéje",
  "Hangszerek és zenekarok kézikönyve",
  "Operák könyve",
  "Operák könyve",
];
